name: Juurikatabcolor
version: @version@
main: eu.mikroskeem.juurikatabcolor.Main
depend: [PermissionsEx]
authors: [mikroskeem]
description: J채rgmine tab v채rvide plugin mis ei ole lihtsalt v채lja situtud, vaid h채sti tehtud. Made on request for Karmo Tutk
website: https://mikroskeem.eu

commands:
  jtc:
    permissions: jtc.reload

permissions:
  jtc.reload:
    default: op